name: PR auto merge
on:
  schedule:
    - cron: '30 14 * * 3' # 매주 수요일 14시(UTC) -> 매주 수요일 23시(KST) 9시간 시차존재
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          MERGE_LABELS: "" # 모든 PR을 병합합니다.
          MERGE_METHOD: "squash" # PR을 스쿼시형태로 병합합니다.
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
